version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5001:5000"
    command: python analysis.py

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    working_dir: /app
    command: python -m unittest discover -s . -p test_analysis.py
